#! /bin/sh

# file      : bootstrap
# license   : GNU GPL v2; see accompanying LICENSE file

#
# Bootstrap the automake build system.
#

rm -f config.cache

if test ! -d m4; then
  mkdir m4
fi

autoreconf --install
