# file      : tests/basics/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

import libs = libodb%lib{odb}

exe{driver}: cxx{driver} $libs
